"""followers

Revision ID: 346b64e5c2ed
Revises: 0ce0c9fb96d5
Create Date: 2020-11-09 09:45:52.503296

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '346b64e5c2ed'
down_revision = '0ce0c9fb96d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
